apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage-class
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
