apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: rc
data:
  redis.conf: |
    bind 0.0.0.0
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode no
    port 6379
