apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-cluster
  labels:
    app: redis
data:
  redis.conf: |
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode no
    port 6379
