apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
spec:
  serviceName: "redis"
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
          - containerPort: 6379
            name: client
          - containerPort: 16379
            name: gossip
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
              readOnly: false
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          resources:
              requests:
                memory: "400Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
      volumes:
        - name: config
          configMap:
            name: redis-config
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        storageClassName: redis-storage-class
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
